server:
  port: 8081
spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
     ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
